version: '3.8'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: 'dSBHpKAHiiFVLkiJCrJO_hPfhzNKr3sKDBo6UhDlHcY='
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    PYTHONPATH: '/opt/airflow/scripts'
    _PIP_ADDITIONAL_REQUIREMENTS: 'pandas psycopg2-binary'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./sql:/opt/airflow/sql
    - ./data:/opt/airflow/data
    - airflow_logs:/opt/airflow/logs
  depends_on:
    postgres_airflow:
      condition: service_healthy

services:

  # ── Database 1: Airflow's own metadata database ──
  postgres_airflow:
    image: postgres:15
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_airflow_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Database 2: Your Data Warehouse ──
  postgres_dwh:
    image: postgres:15
    container_name: postgres_dwh
    environment:
      POSTGRES_USER: dwh_user
      POSTGRES_PASSWORD: dwh_pass
      POSTGRES_DB: ecommerce_dwh
    ports:
      - "5433:5432"
    volumes:
      - postgres_dwh_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dwh_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Airflow: First-time setup ──
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
    restart: on-failure

  # ── Airflow: Web UI ──
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  # ── Airflow: Scheduler (runs DAGs) ──
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres_airflow_db:
  postgres_dwh_db:
  airflow_logs:
